#include "gpio.h"

const PinDef pinList[] = 
{
    [LED_RUN]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS1]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS2]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS3]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS4]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS5]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS6]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS7]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POS8]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FINGER_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FORK_CAM_PSW_1]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FORK_CAM_PSW_2]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FINGER_24V_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [PHY_RST]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [LIGHT_PSW_1]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [LIGHT_PSW_2]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [CAM_3D_LIGH_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [RFID_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [SWITCHES_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [LED_DEBUG_1]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [LED_DEBUG_2]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [LIGH_PSW_REV]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FAN_STATE_DET]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FAN_PSW]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [FINGER_24V_DET]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
//    [POW_DET]   = PIN_DEFINE(E, 10, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_OSPEED_50MHZ, GPIO_OTYPE_PP),
};

static void gpio_clk_config(void)
{
    rcu_periph_clock_enable(RCU_GPIOA);
    rcu_periph_clock_enable(RCU_GPIOB);
    rcu_periph_clock_enable(RCU_GPIOC);
    rcu_periph_clock_enable(RCU_GPIOD);
    rcu_periph_clock_enable(RCU_GPIOE);
    rcu_periph_clock_enable(RCU_GPIOF);
    rcu_periph_clock_enable(RCU_GPIOG);
    rcu_periph_clock_enable(RCU_GPIOH);
    rcu_periph_clock_enable(RCU_GPIOI);
}

void gpio_config(void)
{
    gpio_clk_config();
    for(int i = 0; i < sizeof(pinList)/sizeof(PinDef); i++)
    {
        gpio_mode_set(pinList[i].port, pinList[i].mode, pinList[i].pull, pinList[i].pin);
        gpio_output_options_set(pinList[i].port, pinList[i].otype, pinList[i].speed, pinList[i].pin);
        gpio_bit_reset(pinList[i].port, pinList[i].pin);
    }
}

